### ISSUE TITLE
Random Demotes?

### ISSUE THREAD

**Issue by kulcris** [Nayruden/Ulysses#376] opened 2014-12-15 23:23 UTC
L 12/15/2014 - 17:59:38: Lua Error: ULib queue error: addons/ulx/lua/ulx/modules/sh/fun.lua:679: Tried to use a NULL entity!

last time it happened it was from someone ragdolling themselves. this was spammed into server console (pulled from logs). then they crashed. when they rejoined they had been demoted. i have seen other cases of this with other errors although i am unable to find the other errors (updated yesterday to the beta release to see if it was fixed and it is not)

**Comment by SticklyMan** [comment] 2015-03-08 02:51
Duplicate of #346- very similar symptoms.

**Closed by SticklyMan** 2015-03-08 02:51 UTC
Labels: Duplicate
