### ISSUE TITLE
Causing DarkRP lag and crashes

### ISSUE THREAD

**Issue by roastt** [Nayruden/Ulysses#424] opened 2015-03-14 23:12 UTC
No error, just causing lag and crashes. I made a fresh darkrp vanilla no addons and it was fine then ULX lagged the server and crashed it.

Please hotfix, I need ULX...

**Comment by Nayruden** [comment] 2015-03-15 05:24
Duplicate of #416

**Closed by Nayruden** 2015-03-15 05:24 UTC
Labels: Duplicate
