### ISSUE TITLE
ULX Menu doest not work in latest GMOD update

### ISSUE THREAD

**Issue by PitifulCanine3** [Nayruden/Ulysses#414] opened 2015-03-09 20:33 UTC
Since the latest GMOD update both !menu & !xgui do not work on version 3.61 and doesn't display anything like the command does not exist.

**Comment by SticklyMan** [comment] 2015-03-09 20:33
Duplicate of #408. Already fixed, please search before posting a new issue.

**Closed by SticklyMan** 2015-03-09 20:33 UTC

**Comment by PitifulCanine3** [comment] 2015-03-09 20:37
Sorry, my bad.
