### ISSUE TITLE
Pointshop

### ISSUE THREAD

**Issue by MrUnknownGamer** [Nayruden/Ulysses#457] opened 2015-04-15 04:32 UTC
Im just wondering, you said you would check it out. And theres no fix. Whats going on with it? Im running lunix and getting the same error except its a different line
```
[ERROR] addons/pointshop-master/lua/pointshop/sv_player_extension.lua:287: attempt to index field 'PS_Items' (a nil value)
1. PS_HasItem - addons/pointshop-master/lua/pointshop/sv_player_extension.lua:287
2. PS_HasItemEquipped - addons/pointshop-master/lua/pointshop/sv_player_extension.lua:291
3. fn - addons/pointshop-master/lua/pointshop/sh_init.lua:145
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:107
```

Please keep this open. I really would like to fix this.
Thank You

Running linux, up to date with PS, ULX, and ULIB

:+1: You got this!

**Comment by SticklyMan** [comment] 2015-04-15 15:35
Duplicate of #449 and #450. We have confirmed that the cause is not directly related to ULib, but likely another conflicting addon. Please follow this discussion on our forums to help figure out the root cause:
http://forums.ulyssesmod.net/index.php/topic,8426.0.html

**Closed by SticklyMan** 2015-04-15 15:35 UTC
Labels: Duplicate
