### ISSUE TITLE
ULX !menu does not open

### ISSUE THREAD

**Issue by Skittlez** [Nayruden/Ulysses#419] opened 2015-03-10 19:21 UTC
I manage this deathrun server everything was working fine till yesterday when the command !menu does not open the ulx menu. I tried this in console to, still didn't work. All commands still work but !menu. 

Any ideas to whats causing this. There is no error in console when server loads up, no one has messed with ulx and nothing has been recently added to cause a problem with ulx.

**Comment by Nayruden** [comment] 2015-03-10 19:22
Read the site news, read the other issues, you'll figure it out.

**Comment by SticklyMan** [comment] 2015-03-10 19:26
Duplicate of #408

**Comment by Skittlez** [comment] 2015-03-10 19:26
Ok I just read the news, just got one more question if I re install ulx with the new updated one will that remove all the banned people/groups?

**Closed by SticklyMan** 2015-03-10 19:26 UTC
Labels: Duplicate

**Comment by Nayruden** [comment] 2015-03-10 19:29
No, your config and ban data is not stored in the addons folder.
