### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by deinemudda32** [Nayruden/Ulysses#506] opened 2015-08-23 13:48 UTC
[ERROR] lua/vgui/dmenuoption.lua:73: attempt to call method 'OpenSubMenu' (a nil value)
  1. unknown - lua/vgui/dmenuoption.lua:73

**Comment by Nayruden** [comment] 2015-08-23 14:20
What does this have to do with ULX/ULib?

**Comment by deinemudda32** [comment] 2015-08-23 14:24
Happend as I had the column of groups in the groups panel opened and errord then.
Only clientsidely.

**Comment by Nayruden** [comment] 2015-08-23 14:28
I've linked in our XGUI expert.

**Comment by SticklyMan** [comment] 2015-11-07 21:02
Unable to reproduce this at all- The code itself says it's failing when the mouse entered a DMenuOption (likely the dropdown box at the top of the groups tab). We also have not received many complaints about this, so it was likely a client-side mod causing the issue.

I'm closing this for now, but if you get this issue again, let us know. If you can, look at any commands that may have been run at the time the error occurred.

**Closed by SticklyMan** 2015-11-07 21:02 UTC
Labels: Needs Investigation, XGUI
