### ISSUE TITLE
Pointshop breaks when ULib is installed

### ISSUE THREAD

**Issue by TomatoCo** [Nayruden/Ulysses#450] opened 2015-04-11 02:33 UTC
The error received when ULib is installed is:

```
[ERROR] addons/pointshop/lua/pointshop/sv_player_extension.lua:283: attempt to index field 'PS_Items' (a nil value)
1. PS_HasItem - addons/pointshop/lua/pointshop/sv_player_extension.lua:283
2. PS_hasItemEquipped - addons/pointshop/lua/pointshop/sv_player_extension.lua:287
3. fn - addons/pointshop/lua/pointshop/sh_init.lua:145
4. unknown - addons/ulib/lua/ulib/shared/hook.lua:108
```

HOWEVER! THIS ERROR DOES NOT OCCUR AFTER ULIB IS UNINSTALLED. WHEN ULIB IS INSTALLED, POINTSHOP BREAKS. WHEN ULIB IS NOT INSTALLED, POINTSHOP WORKS.

Just deleting hooks.lua fixes the problem, as well. While I agree that, perhaps, hooks.lua is not the source of the problem, it 100% is involved in the problem and, before hooks.lua overrides the default hook behavior, the Pointshop works fine.

I really need to apologize for the all-caps and immediately recreating the issue, but it is very frustrating to have my original issue closed within a few minutes of creating it when I have been tracking down this bug for the past few days.

**Comment by Nayruden** [comment] 2015-04-11 14:38
Duplicate of #449, duplicates are auto-closed. I'll try installing Pointshop to verify, however.

**Closed by Nayruden** 2015-04-11 14:38 UTC
Labels: Duplicate
